#!/bin/sh

# Set these paths appropriately

BIN="/home/marisolbarrientosmoreno/Desktop/Summer_Semester/i17/deadline/regulatory-documents-tie/temporal_compliance_verificator/src/heideltime/heideltime-standalone/treetagger/bin"
CMD="/home/marisolbarrientosmoreno/Desktop/Summer_Semester/i17/deadline/regulatory-documents-tie/temporal_compliance_verificator/src/heideltime/heideltime-standalone/treetagger/cmd"
LIB="/home/marisolbarrientosmoreno/Desktop/Summer_Semester/i17/deadline/regulatory-documents-tie/temporal_compliance_verificator/src/heideltime/heideltime-standalone/treetagger/lib"

GERMANTAGGER=${CMD}/tree-tagger-german
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german.par
PARFILE2=${LIB}/german-chunker.par
FILTER=${CMD}/filter-chunker-output-german.perl

$GERMANTAGGER $* |
perl -nae 'if ($#F==0){print}else{print "$F[0]-$F[1]\n"}' |
$TAGGER $PARFILE2 -token -sgml -eps 0.00000001 -hyphen-heuristics -quiet |
$FILTER |
$TAGGER -quiet -token -lemma -sgml $PARFILE
