#!/bin/sh

# Set these paths appropriately

BIN="/home/marisolbarrientosmoreno/Desktop/Summer_Semester/i17/deadline/regulatory-documents-tie/temporal_compliance_verificator/src/heideltime/heideltime-standalone/treetagger/bin"
CMD="/home/marisolbarrientosmoreno/Desktop/Summer_Semester/i17/deadline/regulatory-documents-tie/temporal_compliance_verificator/src/heideltime/heideltime-standalone/treetagger/cmd"
LIB="/home/marisolbarrientosmoreno/Desktop/Summer_Semester/i17/deadline/regulatory-documents-tie/temporal_compliance_verificator/src/heideltime/heideltime-standalone/treetagger/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
